import colorama
from colorama import Fore, Style

colorama.init(autoreset=True)

R = Fore.RED + Style.BRIGHT
G = Fore.GREEN + Style.BRIGHT
Y = Fore.YELLOW + Style.BRIGHT
B = Fore.BLUE + Style.BRIGHT
M = Fore.MAGENTA + Style.BRIGHT
C = Fore.CYAN + Style.BRIGHT
W = Fore.WHITE + Style.BRIGHT
RR = Style.RESET_ALL
BLDR = Style.BRIGHT

SQL_DORKS = [
    "inurl:index.php?id=",
    "inurl:news.php?id=",
    "inurl:article.php?id=",
    "inurl:category.php?id=",
    "inurl:categories.php?id=",
    "inurl:detail.php?id=",
    "inurl:prod.php?id=",
    "inurl:product.php?pid=",
    "inurl:items.php?id=",
    "inurl:book.php?id=",
    "inurl:offer.php?id=",
    "inurl:purchase.php?id=",
    "inurl:buy.php?id=",
    "inurl:shop_item.php?id=",
    "inurl:more.php?id=",
    "inurl:phpinfo.php",
    "inurl:test.php?id=",
    "inurl:info.php?id=",
    "inurl:readnews.php?id=",
    "inurl:top10.php?cat=",
    "inurl:aboutbook.php?id=",
    "inurl:review.php?id=",
    "inurl:material.php?id=",
    "inurl:opinions.php?id=",
    "inurl:spr.php?id=",
    "inurl:pages.php?id=",
    "inurl:announce.php?id=",
    "inurl:clanek.php?id=",
    "inurl:participant.php?id=",
    "inurl:download.php?id=",
    "inurl:main.php?pid=",
    "inurl:rub.php?idr=",
    "inurl:view_faq.php?faq_id=",
    "inurl:clubpage.php?id=",
    "inurl:memberlist.php?mode=",
    "inurl:projects.php?id=",
    "inurl:faq2.php?id=",
    "inurl:show_an.php?id=",
    "inurl:preview.php?id=",
    "inurl:book_details.php?book_id=",
    "inurl:artist.php?id=",
    "inurl:enc detail.php?ID=",
    "inurl:holiday package.php?id=",
    "inurl:desktopdefault.aspx?alias=",
    "inurl:community.aspx?cat=",
    "inurl:mall.php?ProdID=",
    "inurl:productdetail.aspx?prod=",
    "inurl:viewthread.php?tid=",
    "intext:\"You have an error in your SQL syntax near\"",
    "intext:\"supplied argument is not a valid MySQL result\"",
    "intext:\"mysql_fetch_object(): supplied argument\"",
    "intext:\"on line <b>\"",
    "intext:\"Dynamic content from database\"",
    "intext:\"mysql_pconnect\"",
    "filetype:sql \"MySQL dump\" (password|pass|pwd|user)",
    "filetype:sql \"insert into\" \"values\"",
    "filetype:sql \"create database\"",
    "filetype:sql \"drop table\"",
    "intitle:\"index of\" \"parent directory\" \"sql\"",
    "intitle:\"index of\" db_backup OR database_backup",
    "inurl:database.sql OR inurl:db.sql",
    "inurl:dump.sql.gz OR inurl:backup.sql.gz",
    "inurl:admin/config.php",
    "inurl:administrator/components/com_config",
    "inurl:configuration.php.dist",
    "inurl:.htaccess.bak",
    "inurl:web.config.bak",
    "filetype:env \"DB_HOST\"",
    "filetype:yaml \"database_password\"",
    "filetype:conf \"password\"",
    "intext:\"phpMyAdmin\" \"running on\"",
    "inurl:/phpmyadmin/scripts/setup.php",
    "intitle:\"phpMyAdmin\" \"localhost\"",
    "inurl:sqlitemanager.php",
    "inurl:adminer.php",
    "inurl:dbadmin.php",
    "inurl:myadmin/index.php",
    "intext:\"Warning: array_merge()\"",
    "intext:\"Warning: preg_match()\"",
    "intext:\"Warning: ilesize():\"",
    "intext:\"Microsoft JET Database Engine\"",
    "intext:\"ODBC SQL Server Driver\"",
    "intext:\"Sybase message\"",
    "intext:\"Incorrect syntax near\"",
    "intext:\"Unclosed quotation mark\"",
    "intext:\"quoted string not properly terminated\"",
    "inurl:page.php?id=",
    "inurl:content.php?id=",
    "inurl:story.php?id=",
    "inurl:post.php?id=",
    "inurl:blog.php?id=",
    "inurl:entry.php?id=",
    "inurl:view.php?id=",
    "inurl:show.php?id=",
    "inurl:profile.php?id=",
    "inurl:user.php?id=",
    "inurl:member.php?id=",
    "inurl:staff.php?id=",
    "inurl:employee.php?id=",
    "inurl:customer.php?id=",
    "inurl:order.php?id=",
    "inurl:invoice.php?id=",
    "inurl:bill.php?id=",
    "inurl:receipt.php?id=",
    "inurl:cart.php?item=",
    "inurl:checkout.php?id=",
    "inurl:product_detail.php?prodid=",
    "inurl:item_detail.php?itemid=",
    "inurl:prod_detail.php?id=",
    "inurl:goods.php?id=",
    "inurl:shop.php?pid=",
    "inurl:store.php?product=",
    "inurl:category.php?catid=",
    "inurl:subcat.php?id=",
    "inurl:gallery.php?id=",
    "inurl:photo.php?id=",
    "inurl:image.php?id=",
    "inurl:album.php?id=",
    "inurl:video.php?id=",
    "inurl:media.php?id=",
    "inurl:download.php?file=",
    "inurl:file.php?id=",
    "inurl:doc.php?id=",
    "inurl:pdf.php?id=",
    "inurl:report.php?id=",
    "inurl:forum.php?thread=",
    "inurl:thread.php?id=",
    "inurl:topic.php?id=",
    "inurl:message.php?id=",
    "inurl:comment.php?id=",
    "inurl:review.php?pid=",
    "inurl:rate.php?id=",
    "inurl:vote.php?id=",
    "inurl:poll.php?id=",
    "inurl:survey.php?id=",
    "inurl:event.php?id=",
    "inurl:calendar.php?event=",
    "inurl:job.php?id=",
    "inurl:career.php?id=",
    "inurl:resume.php?id=",
    "inurl:cv.php?id=",
    "inurl:project.php?id=",
    "inurl:case.php?id=",
    "inurl:study.php?id=",
    "inurl:paper.php?id=",
    "inurl:thesis.php?id=",
    "inurl:publication.php?id=",
    "inurl:author.php?id=",
    "inurl:book.php?ISBN=",
    "inurl:magazine.php?id=",
    "inurl:newspaper.php?id=",
    "inurl:press.php?id=",
    "inurl:announcement.php?id=",
    "inurl:notice.php?id=",
    "inurl:advert.php?id=",
    "inurl:banner.php?id=",
    "inurl:promo.php?id=",
    "inurl:coupon.php?id=",
    "inurl:deal.php?id=",
    "inurl:sale.php?id=",
    "inurl:discount.php?id=",
    "inurl:auction.php?id=",
    "inurl:bid.php?id=",
    "inurl:news_detail.php?id=",
    "inurl:article_details.php?id=",
    "inurl:product.php?product_id=",
    "inurl:item.php?item_id=",
    "inurl:view_product.php?id=",
    "inurl:show_product.php?id=",
    "inurl:details.php?prod=",
    "inurl:info.php?item=",
    "inurl:read.php?id=",
    "inurl:display.php?id=",
    "inurl:list.php?cat=",
    "inurl:category_view.php?cat=",
    "inurl:cat.php?id=",
    "inurl:subcategory.php?sub=",
    "inurl:section.php?id=",
    "inurl:page_id=",
    "inurl:pid=",
    "inurl:cid=",
    "inurl:mid=",
    "inurl:nid=",
    "inurl:tid=",
    "inurl:sid=",
    "inurl:rid=",
    "inurl:aid=",
    "inurl:eid=",
    "inurl:uid=",
    "inurl:code=",
    "inurl:ref=",
    "inurl:num=",
    "inurl:no=",
    "inurl:key=",
    "inurl:record=",
    "inurl:row=",
    "inurl:entry_id=",
    "inurl:object_id=",
    "inurl:content_id=",
    "inurl:resource_id=",
    "inurl:articleid=",
    "inurl:newsid=",
    "inurl:postid=",
    "inurl:topicid=",
    "inurl:threadid=",
    "inurl:forumid=",
    "inurl:groupid=",
    "inurl:dept=",
    "inurl:department=",
    "inurl:branch=",
    "inurl:location=",
    "inurl:region=",
    "inurl:country=",
    "inurl:state=",
    "inurl:city=",
    "inurl:zip=",
    "inurl:postal=",
    "inurl:area=",
    "inurl:zone=",
    "inurl:sector=",
    "inurl:module=",
    "inurl:component=",
    "inurl:option=",
    "inurl:task=",
    "inurl:action=",
    "inurl:function=",
    "inurl:mode=",
    "inurl:type=",
    "inurl:viewtype=",
    "inurl:layout=",
    "inurl:template=",
    "inurl:skin=",
    "inurl:theme=",
    "inurl:lang=",
    "inurl:language=",
    "inurl:session=",
    "inurl:sessid=",
    "inurl:PHPSESSID=",
    "inurl:token=",
    "inurl:auth=",
    "inurl:login.php?redirect=",
    "inurl:redirect.php?url=",
    "inurl:goto.php?url=",
    "inurl:link.php?url=",
    "inurl:jump.php?url=",
    "inurl:out.php?url=",
    "inurl:frame.php?url=",
    "inurl:open.php?url=",
    "inurl:viewfile.php?file=",
    "inurl:download.php?path=",
    "inurl:getfile.php?file=",
    "inurl:load.php?file=",
    "inurl:include.php?file=",
    "inurl:require.php?file=",
    "inurl:page.php?file=",
    "inurl:content.php?page=",
    "inurl:print.php?id=",
    "inurl:pdfgen.php?id=",
    "inurl:export.php?id=",
    "inurl:backup.php",
    "inurl:restore.php",
    "inurl:import.php",
    "inurl:admin/backup",
    "inurl:admin/export",
    "inurl:admin/database",
    "inurl:admin/db",
    "inurl:admin/sql",
    "inurl:admin/dump",
    "inurl:admin/restore",
    "intext:\"You have an error in your SQL syntax\"",
    "intext:\"SQL syntax near '\"",
    "intext:\"mysql_num_rows()\"",
    "intext:\"mysql_result()\"",
    "intext:\"mysql_affected_rows()\"",
    "intext:\"Warning: mysql_connect()\"",
    "intext:\"Warning: mysql_query()\"",
    "intext:\"Warning: pg_query()\"",
    "intext:\"Warning: mssql_query()\"",
    "intext:\"Microsoft OLE DB Provider for SQL Server\"",
    "intext:\"SQL Server Driver\"",
    "intext:\"PostgreSQL query failed\"",
    "intext:\"SQLite3::SQLException\"",
    "intext:\"near \\\"\\\" syntax error\"",
    "intext:\"Unclosed quotation mark after the character string\"",
    "intext:\"String or binary data would be truncated\"",
    "intext:\"Conversion failed when converting the nvarchar value\"",
    "intext:\"The used SELECT statements have a different number of columns\"",
    "intext:\"ORA-\" \"SQL\"",
    "intext:\"PLS-\" \"PL/SQL\"",
    "intext:\"SQLSTATE\"",
    "intext:\"[Microsoft][ODBC\"",
    "intext:\"java.sql.SQLException\"",
    "intext:\"SQL error\" \"near\"",
    "intext:\"database error\" \"query failed\"",
    "filetype:sql site:*.com | site:*.org | site:*.net -inurl:(login signup register)",
    "filetype:sql \"-- MySQL dump\" \"password\"",
    "filetype:sql \"-- phpMyAdmin SQL Dump\"",
    "filetype:sql intext:\"CREATE TABLE\"",
    "filetype:sql intext:\"INSERT INTO `users`\"",
    "filetype:sql intext:\"INSERT INTO `admin`\"",
    "filetype:bak intext:\"MySQL\"",
    "filetype:gz intext:\"MySQL dump\"",
    "filetype:sql.gz",
    "filetype:sql.zip",
    "inurl:backup filetype:sql",
    "inurl:dump filetype:sql",
    "inurl:db filetype:sql",
    "inurl:database filetype:sql",
    "inurl:sql filetype:txt \"password\"",
    "inurl:config filetype:sql \"root\"",
    "intitle:\"index of\" \"backup.sql\"",
    "intitle:\"index of\" \"database.sql\"",
    "intitle:\"index of\" \"db_dump.sql\"",
    "intitle:\"index of\" \"full_db.sql\"",
    "intitle:\"index of\" \"prod.sql\"",
    "intitle:\"index of\" \"staging.sql\"",
    "intitle:\"index of\" \"test.sql\"",
    "intitle:\"index of\" \"users.sql\"",
    "intitle:\"index of\" \"wp_users.sql\"",
    "intitle:\"index of\" \"backup_\"",
    "intitle:\"index of\" \"dump_\"",
    "intitle:\"index of\" \"sql_\"",
    "intitle:\"index of\" \"db_backup\"",
    "intitle:\"index of\" \"mysql.bak\"",
    "intitle:\"index of\" \"database_backup\"",
    "filetype:env \"DB_PASSWORD\"",
    "filetype:env \"DATABASE_URL\"",
    "filetype:env \"MYSQL_ROOT_PASSWORD\"",
    "filetype:ini \"mysql\" \"password\"",
    "filetype:conf \"mysql\" \"pass\"",
    "inurl:config/database.php",
    "inurl:config/db.php",
    "inurl:includes/config.php",
    "inurl:application/config/database.php",
    "inurl:config/database.yml",
    "inurl:config/secrets.yml",
    "inurl:.env \"DB_USERNAME\"",
    "inurl:.env.example \"DB_PASSWORD\"",
    "inurl:wp-config.php \"DB_PASSWORD\"",
    "inurl:configuration.php \"var $password\"",
    "inurl:settings.php \"database\" \"password\"",
    "inurl:localsettings.php \"wgDBpassword\"",
    "inurl:configuration.php \"password\"",
    "inurl:db_connect.php",
    "inurl:connect.php \"mysql\"",
    "inurl:db.php \"password\"",
    "inurl:database.php \"pass\"",
]

LOG_DORKS = [
    "filetype:log \"access.log\"",
    "filetype:log \"error.log\"",
    "filetype:log \"common.log\"",
    "filetype:log \"combined.log\"",
    "filetype:log \"ssl_access.log\"",
    "filetype:log \"ssl_error.log\"",
    "filetype:log intext:\"GET /\"",
    "filetype:log intext:\"POST /\"",
    "filetype:log intext:\"auth.log\"",
    "filetype:log intext:\"syslog\"",
    "filetype:log intext:\"daemon.log\"",
    "filetype:log intext:\"client_ip\"",
    "filetype:log intext:\"remote_addr\"",
    "filetype:log intext:\"x-forwarded-for\"",
    "filetype:log intext:\"user-agent\"",
    "intitle:\"index of\" \"access.log\"",
    "intitle:\"index of\" \"error.log\"",
    "intitle:\"index of\" \"logs/\"",
    "intitle:\"index of\" \"log/\"",
    "inurl:\"/logs/access.log\"",
    "inurl:\"/logs/error.log\"",
    "inurl:\"/log/access.log\"",
    "inurl:\"/log/error.log\"",
    "filetype:txt \"IP Address\" \"User Agent\" \"Referer\"",
    "filetype:log \"failed login\"",
    "filetype:log \"Accepted password for\"",
    "filetype:log \"ssh-rsa\"",
    "filetype:log \"Connection from\"",
    "intext:\"web server logs\" \"index of /\"",
    "ext:log intext:\"host:\" intext:\"ip:\"",
    "allinurl:/var/log/",
]

IP_DORKS = [
    "inurl:view/view.shtml",
    "inurl:view/index.shtml",
    "inurl:ViewerFrame?Mode=Motion",
    "inurl:axis-cgi/mjpg",
    "inurl:mjpg/video.mjpg",
    "inurl:video/mjpg.cgi",
    "inurl:/jpg/image.jpg",
    "inurl:/axis-cgi/jpg/image.cgi",
    "inurl:/axis-cgi/mjpg",
    "inurl:/viewer/live/en/live.html",
    "inurl:/viewer/index.html",
    "inurl:/view.shtml?imagepath=",
    "inurl:/MultiCamera.htm",
    "inurl:/guestimage.html",
    "inurl:/video.cgi",
    "inurl:/snap.jpg",
    "inurl:/image/jpeg.cgi",
    "inurl:/camera.jpg",
    "inurl:/img/snapshot.cgi",
    "inurl:/Streaming/channels/1/picture",
    "intitle:\"Live View / - AXIS\"",
    "intitle:\"AXIS 210 Network Camera\"",
    "intitle:\"AXIS M10\"",
    "intitle:\"D-Link Internet Camera\"",
    "intitle:\"DCS-930L\"",
    "intitle:\"mydlink\"",
    "intitle:\"Foscam\" \"username\"",
    "intitle:\"Foscam\" inurl:admin",
    "intitle:\"WebcamXP\" \"MJPG\"",
    "intitle:\"Blue Iris\" \"admin\"",
    "intitle:\"iSpy\" \"web server\"",
    "intitle:\"Network Camera\" \"login\"",
    "intitle:\"Panasonic Network Camera\"",
    "intitle:\"Sony Network Camera\"",
    "intitle:\"SNC-CH110\"",
    "inurl:\"/view/viewer_index.shtml\"",
    "inurl:\"/CgiStart?page=\"",
    "inurl:\"/viewer/live/index.html\"",
    "inurl:\"/control/userimage.html\"",
    "inurl:\"/snapshot.cgi?user=\"",
    "inurl:\"/axis-cgi/com/view.cgi\"",
    "inurl:\"/mjpg/video.cgi\"",
    "inurl:\"/video.mjpg\"",
    "inurl:\"/videostream.cgi\"",
    "inurl:\"/cam_pic.php\"",
    "inurl:\"/camera.asp\"",
    "inurl:\"/live.htm\"",
    "inurl:\"/live.jhtml\"",
    "inurl:\"/singleframe.cgi\"",
    "inurl:\"/image/jpeg.cgi\"",
    "inurl:\"/jpg/1/image.jpg\"",
    "intitle:\"Live NetSnap Cam-Server\"",
    "intitle:\"Webcam 7\"",
    "intitle:\"Yawcam\"",
    "intitle:\"i-Catcher\"",
    "intitle:\"MOBOTIX\"",
    "intitle:\"NetworkCamera\"",
    "intitle:\"DVR WebClient\"",
    "intitle:\"Geovision\"",
    "intitle:\"Hikvision\"",
    "intitle:\"Dahua\"",
    "intitle:\"Trendnet\"",
    "intitle:\"Wanscam\"",
    "intitle:\"Linksys\"",
    "intitle:\"WVC54G\"",
    "inurl:\"/video.cgi?resolution=\"",
    "inurl:\"/cgi-bin/view.cgi\"",
    "inurl:\"/image1.jpg\"",
    "inurl:\"/shot.jpg\"",
    "inurl:\"/temp.jpg\"",
    "inurl:\"/live_feed.cgi\"",
    "inurl:\"/cam.mjpg\"",
    "inurl:\"/video_feed.cgi\"",
    "inurl:\"/live/video\"",
    "inurl:/live/view.php",
    "inurl:/live.php",
    "inurl:/viewlive.html",
    "inurl:/view.jsp",
    "inurl:/liveview.cgi",
    "inurl:/live_view.cgi",
    "inurl:/stream.mjpg",
    "inurl:/video.mjpg?resolution=",
    "inurl:/mjpg/video.mjpg?camera=",
    "inurl:/jpg/video.jpg",
    "inurl:/image.mjpeg",
    "inurl:/mjpeg.cgi",
    "inurl:/videostream.cgi?user=",
    "inurl:/videostream.cgi?pwd=",
    "inurl:/cam1.mjpg",
    "inurl:/cam.mjpg",
    "inurl:/video_feed.mjpg",
    "inurl:/snapshot.jpg?user=",
    "inurl:/snap.cgi",
    "inurl:/image/snapshot.cgi",
    "inurl:/jpg/image.jpg?size=",
    "inurl:/image/jpeg.cgi?chn=",
    "inurl:/media/video.mp4",
    "inurl:/h264.cgi",
    "inurl:/onvif/device_service",
    "inurl:/onvif/snapshot",
    "inurl:/snapshot.jpg",
    "inurl:/jpg/now.jpg",
    "inurl:/current.jpg",
    "inurl:/image_now.jpg",
    "inurl:/live/snapshot.jpg",
    "inurl:/img/current.jpg",
    "inurl:/pic/snapshot.jpg",
    "inurl:/capture.jpg",
    "inurl:/cam.jpg",
    "inurl:/img/cam.jpg",
    "inurl:/video/snapshot",
    "intitle:\"Hikvision\" \"live view\"",
    "intitle:\"Hik-Connect\"",
    "intitle:\"Dahua\" \"web viewer\"",
    "intitle:\"Dahua\" inurl:webcaps",
    "intitle:\"Uniview\"",
    "intitle:\"Tiandy\"",
    "intitle:\"XMeye\"",
    "intitle:\"XMEye\" \"login\"",
    "intitle:\"V380\"",
    "intitle:\"CamHi\"",
    "intitle:\"Reolink\"",
    "intitle:\"Amcrest\"",
    "intitle:\"Swann\" \"security\"",
    "intitle:\"Lorex\"",
    "intitle:\"Night Owl\"",
    "intitle:\"Q-See\"",
    "intitle:\"Zosi\"",
    "intitle:\"Annke\"",
    "intitle:\"EZVIZ\"",
    "intitle:\"Imou\"",
    "intitle:\"TP-Link\" \"IP Camera\"",
    "intitle:\"Tenda\" \"webcam\"",
    "intitle:\"Netwave\" \"IP Camera\"",
    "intitle:\"Vivotek\"",
    "intitle:\"Vivotek\" \"Network Camera\"",
    "intitle:\"ACTi\"",
    "intitle:\"Arecont\"",
    "intitle:\"Bosch\" \"Video SDK\"",
    "intitle:\"Hanwha Techwin\"",
    "intitle:\"Samsung Techwin\"",
    "intitle:\"Samsung IP Camera\"",
    "intitle:\"Hikvision DS-\"",
    "intitle:\"Dahua IPC-\"",
    "intitle:\"Dahua DH-\"",
    "intitle:\"Hikvision DS-2CD\"",
    "intitle:\"Dahua DH-SD\"",
    "intitle:\"Hikvision\" \"User Name\"",
    "intitle:\"Dahua\" \"username\"",
    "intitle:\"EZVIZ\" \"live view\"",
    "intitle:\"Reolink\" \"camera\"",
    "intitle:\"Amcrest\" \"web\"",
    "intitle:\"Foscam FI\"",
    "intitle:\"Wansview\"",
    "intitle:\"Yoosee\"",
    "intitle:\"HDCView\"",
    "intitle:\"iCSee\"",
    "intitle:\"CamHi Pro\"",
    "intitle:\"Web Viewer for DVR\"",
    "intitle:\"DVR WebClient\"",
    "intitle:\"CMS\" \"login\"",
    "intitle:\"NetDVR\"",
    "intitle:\"Multi画面\"",
    "intitle:\"XVR\"",
    "intitle:\"Hybrid NVR\"",
    "intitle:\"NVR Login\"",
    "inurl:/web/index.html",
    "inurl:/web/client.html",
    "inurl:/web/login.asp",
    "inurl:/ui/login.action",
    "inurl:/viewer/live/en/live.html",
    "inurl:/DVR.cfg",
    "inurl:/NVR.cfg",
    "inurl:/default.cfg",
    "intitle:\"GeoVision\"",
    "intitle:\"Blue Iris\"",
    "intitle:\"ZoneMinder\"",
    "intitle:\"Shinobi\"",
    "intitle:\"motionEye\"",
    "intitle:\"iSpy\"",
    "intitle:\"Webcam 7\"",
    "intitle:\"WAGO WebVisu\"",
    "intitle:\"Siemens Simatic S7\"",
    "intitle:\"SCADA System\"",
    "intitle:\"Remote Desktop Web Connection\"",
    "inurl:top.htm inurl:currenttime",
    "intitle:\"SonicWALL\" inurl:config",
    "intitle:\"Brother\" \"Web Based Management\"",
    "intitle:\"hp lexmark\" \"inbound faxes\"",
    "intitle:\"Dashboard [Jenkins]\"",
    "inurl:/git/config",
    "inurl:/svn/entries",
    "inurl:/druid/index.html",
    "intitle:\"Kibana\" inurl:5601",
    "intitle:\"Grafana\" inurl:3000",
]

XSS_DORKS = [
    "inurl:search.php?q=",
    "inurl:search.php?s=",
    "inurl:search.php?query=",
    "inurl:search.php?keyword=",
    "inurl:results.php?search=",
    "inurl:search.aspx?q=",
    "inurl:view.php?name=",
    "inurl:index.php?name=",
    "inurl:welcome.php?name=",
    "inurl:login.php?msg=",
    "inurl:error.php?msg=",
    "inurl:checkout.php?msg=",
    "inurl:faq.php?question=",
    "inurl:contact.php?email=",
    "inurl:subscribe.php?email=",
    "inurl:newsletter.php?email=",
    "inurl:redir.php?url=",
    "inurl:redirect.php?url=",
    "inurl:view.php?file=",
    "inurl:go.php?to=",
    "inurl:return.php?url=",
    "inurl:return_to=",
    "inurl:back_url=",
    "inurl:cancel_url=",
    "inurl:success_url=",
    "inurl:next=",
    "inurl:prev=",
    "inurl:page?name=",
    "inurl:view?id=",
    "inurl:show?id=",
    "inurl:item?id=",
    "inurl:cat?id=",
    "inurl:lang=",
    "inurl:locale=",
    "inurl:viewsource.php?file=",
    "inurl:edit.php?file=",
    "inurl:modify.php?id=",
    "inurl:delete.php?id=",
    "inurl:update.php?id=",
    "inurl:submit.php?id=",
    "inurl:preview.php?id=",
    "inurl:print.php?id=",
    "inurl:download.php?id=",
    "inurl:mail.php?id=",
    "inurl:send.php?id=",
    "inurl:forward.php?id=",
    "inurl:reply.php?id=",
    "inurl:feedback.php?id=",
    "inurl:comment.php?id=",
    "inurl:post.php?id=",
    "inurl:article.php?id=",
    "inurl:news.php?id=",
    "inurl:blog.php?id=",
    "inurl:user.php?id=",
    "inurl:profile.php?id=",
    "inurl:member.php?id=",
    "inurl:account.php?id=",
    "inurl:settings.php?id=",
    "inurl:config.php?id=",
    "inurl:setup.php?id=",
    "inurl:install.php?id=",
    "inurl:admin.php?id=",
    "inurl:panel.php?id=",
    "inurl:dashboard.php?id=",
    "inurl:manage.php?id=",
    "inurl:view_item.php?item=",
    "inurl:show_item.php?item=",
    "inurl:get_item.php?item=",
    "inurl:list_item.php?item=",
    "inurl:search_item.php?item=",
    "inurl:filter_item.php?item=",
    "inurl:sort_item.php?item=",
    "inurl:order_item.php?item=",
    "inurl:cat_id=",
    "inurl:subcat_id=",
    "inurl:prod_id=",
    "inurl:product_id=",
    "inurl:sku=",
    "inurl:asin=",
    "inurl:isbn=",
    "inurl:ean=",
    "inurl:upc=",
    "inurl:tag=",
    "inurl:tags=",
    "inurl:label=",
    "inurl:category=",
    "inurl:department=",
    "inurl:division=",
    "inurl:section=",
    "inurl:module=",
    "inurl:plugin=",
    "inurl:component=",
    "inurl:extension=",
    "inurl:theme=",
    "inurl:template=",
    "inurl:layout=",
    "inurl:skin=",
    "inurl:style=",
    "inurl:css=",
    "inurl:js=",
    "inurl:script=",
    "inurl:action=",
    "inurl:method=",
    "inurl:func=",
    "inurl:task=",
    "inurl:step=",
    "inurl:stage=",
    "inurl:level=",
    "inurl:rank=",
    "inurl:score=",
    "inurl:points=",
    "inurl:amount=",
    "inurl:price=",
    "inurl:qty=",
    "inurl:quantity=",
    "inurl:total=",
    "inurl:tax=",
    "inurl:shipping=",
    "inurl:discount=",
    "inurl:coupon=",
    "inurl:promo=",
    "inurl:code=",
    "inurl:token=",
    "inurl:key=",
    "inurl:auth=",
    "inurl:session=",
    "inurl:sid=",
    "inurl:uid=",
    "inurl:guid=",
    "inurl:uuid=",
    "inurl:request_id=",
    "inurl:correlation_id=",
    "inurl:tracking_id=",
    "inurl:order_id=",
    "inurl:invoice_id=",
    "inurl:transaction_id=",
    "inurl:payment_id=",
    "inurl:billing_id=",
    "inurl:customer_id=",
    "inurl:client_id=",
    "inurl:vendor_id=",
    "inurl:supplier_id=",
    "inurl:partner_id=",
    "inurl:affiliate_id=",
    "inurl:referral_id=",
    "inurl:campaign_id=",
    "inurl:source_id=",
    "inurl:medium_id=",
    "inurl:content_id=",
    "inurl:term_id=",
]

R = Fore.RED
G = Fore.GREEN
B = Fore.BLUE
Y = Fore.YELLOW
C = Fore.CYAN
M = Fore.MAGENTA
W = Fore.WHITE
K = Fore.BLACK
RR = Style.RESET_ALL


BANNER = f"""
{C}                           ▀██▀▀█▄                   ▀██      ▀██▀▀█▄                          
{C}                            ██   ██    ▄▄▄   ▄▄▄ ▄▄   ██  ▄▄   ██   ██  ▄▄▄▄    ▄▄▄▄    ▄▄▄▄  
{C}                            ██    ██ ▄█  ▀█▄  ██▀ ▀▀  ██ ▄▀    ██▀▀▀█▄  ▀▀ ▄██  ██▄ ▀  ▄█▄▄▄██ 
{C}                            ██    ██ ██   ██  ██      ██▀█▄    ██    ██ ▄█▀ ██  ▄ ▀█▄▄ ██      
{C}                           ▄██▄▄▄█▀   ▀█▄▄█▀ ▄██▄    ▄██▄ ██▄ ▄██▄▄▄█▀  ▀█▄▄▀█▀ █▀▄▄█▀  ▀█▄▄▄▀ 
"""

HELP_TEXT = f"""
                                   {C}  ██{RR}  -credits       -  shows credits                   {C}  ██{RR}
                                   {C}  ██{RR}  -exit          -  exits tool                      {C}  ██{RR}
                                   {C}  ██{RR}  -help          -  displays this page              {C}  ██{RR}
                                   {C}  ██{RR}  -dorks         -  shows all categories            {C}  ██{RR}
                                   {C}  ██{RR}  -sql / -sql dorks  -  SQL dorks                   {C}  ██{RR}
                                   {C}  ██{RR}  -log / -log dorks  -  Log dorks (good for IPs)    {C}  ██{RR}
                                   {C}  ██{RR}  -ip  / -ip dorks   -  IP cams & devices           {C}  ██{RR}
                                   {C}  ██{RR}  -xss / -xss dorks  -  XSS dorks                   {C}  ██{RR}
"""

CREDITS_TEXT = f"""
                                   {C}╔═════════════════════════════════════════════════╗{RR}
                                   {C}║{RR}  MidnightsAPIstuff     -  developer             {C}║{RR}
                                   {C}║{RR}  back                  -  exits page            {C}║{RR}
                                   {C}╚═════════════════════════════════════════════════╝{RR}
"""
